### ISSUE TITLE
Make encoding options non mandatory

### ISSUE THREAD

**Issue by edubart** [guidanoli/cmioc#41]
At the moment all options like (`--prev-randao`) are mandatory when encoding, would be nice if there a way for them to be automatically filled with zeros.

So I could do:
```
cmioc encode input --binary --auto-fill > input-0.bin
```

Instead of:
```
cmioc encode input --binary \
    --chain-id 0 \
    --app-contract 0x0000000000000000000000000000000000000000 \
    --msg-sender 0x0000000000000000000000000000000000000000 \
    --block-number 0 \
    --block-timestamp 0 \
    --prev-randao 0 \
    --index 0 \
    --payload 0x > input-0.bin
```

Where `--auto-fill` would permit forgetting missing options. But in case  `--index` or `--payload` is passed, it is overwritten. Maybe no need to add `--auto-fill`, and make this the default behavior.

**Comment by guidanoli** [comment]
> would be nice if there a way for them to be automatically filled with zeros.

Why would it be nice?

**Comment by edubart** [comment]
The motivation was to reduce lines of code in some tests scripts, but nervemind, no need this.
